<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net481</TargetFramework>
		<OutputType>Library</OutputType>
		<RootNamespace>PersistentJobsMod</RootNamespace>
		<AssemblyName>PersistentJobsMod</AssemblyName>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<LangVersion>latest</LangVersion>
		<Deterministic>true</Deterministic>
		<OutputPath Condition="'$(Configuration)' == 'Debug'">bin\Debug\</OutputPath>
		<OutputPath Condition="'$(Configuration)' == 'Release'">bin\Release\</OutputPath>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)' == 'Debug'">
		<DebugSymbols>true</DebugSymbols>
		<DebugType>portable</DebugType>
		<Optimize>false</Optimize>
		<DefineConstants>DEBUG;TRACE</DefineConstants>
		<ErrorReport>prompt</ErrorReport>
		<WarningLevel>4</WarningLevel>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)' == 'Release'">
		<DebugType>pdbonly</DebugType>
		<Optimize>true</Optimize>
		<DefineConstants>TRACE</DefineConstants>
		<ErrorReport>prompt</ErrorReport>
		<WarningLevel>4</WarningLevel>
	</PropertyGroup>
	<!--
	Game / Unity references.
  -->
	<ItemGroup>
		<Reference Include="0Harmony">
			<Private>False</Private>
		</Reference>
		<Reference Include="Assembly-CSharp">
			<Private>False</Private>
		</Reference>
		<Reference Include="CommandTerminal">
			<Private>False</Private>
		</Reference>
		<Reference Include="DV.BrakeSystem">
			<Private>False</Private>
		</Reference>
		<Reference Include="DV.Common">
			<Private>False</Private>
		</Reference>
		<Reference Include="DV.PointSet">
			<Private>False</Private>
		</Reference>
		<Reference Include="DV.RailTrack">
			<Private>False</Private>
		</Reference>
		<Reference Include="DV.ThingTypes">
			<Private>False</Private>
		</Reference>
		<Reference Include="DV.Utils">
			<Private>False</Private>
		</Reference>
		<Reference Include="DV.UIFramework">
			<Private>False</Private>
		</Reference>
		<Reference Include="DV.OriginShiftInfo">
			<Private>False</Private>
		</Reference>
		<Reference Include="DV.UI">
			<Private>False</Private>
		</Reference>
		<Reference Include="DV.UserManagement">
			<Private>False</Private>
		</Reference>
		<Reference Include="MessageBox">
			<Private>False</Private>
		</Reference>
		<Reference Include="RSG.Promise">
			<Private>False</Private>
		</Reference>
		<Reference Include="Newtonsoft.Json">
			<Private>False</Private>
		</Reference>
		<Reference Include="UnityEngine">
			<Private>False</Private>
		</Reference>
		<Reference Include="UnityEngine.CoreModule">
			<Private>False</Private>
		</Reference>
		<Reference Include="UnityEngine.IMGUIModule">
			<Private>False</Private>
		</Reference>
		<Reference Include="UnityEngine.TextRenderingModule">
			<Private>False</Private>
		</Reference>
		<Reference Include="UnityEngine.PhysicsModule">
			<Private>False</Private>
		</Reference>
		<Reference Include="UnityEngine.UI">
			<Private>False</Private>
		</Reference>
		<Reference Include="Unity.Mathematics">
			<Private>False</Private>
		</Reference>
		<Reference Include="Unity.Transforms">
			<Private>False</Private>
		</Reference>
		<Reference Include="UnityModManager">
			<Private>False</Private>
		</Reference>
	</ItemGroup>
	<!--
	Krafs.Publicizer
  -->
	<ItemGroup>
		<PackageReference Include="Krafs.Publicizer" Version="2.2.1" PrivateAssets="all" IncludeAssets="runtime; build; native; contentfiles; analyzers" />
	</ItemGroup>
	<!--
	Krafs.Publicizer configuration.
  -->
	<ItemGroup>
		<Publicize Include="Assembly-CSharp:DV.Console.MoveCarsCoro" />
		<Publicize Include="Assembly-CSharp:EmptyHaulJobProceduralGenerator.CalculateBonusTimeLimitAndWage" />
		<Publicize Include="Assembly-CSharp:EmptyHaulJobProceduralGenerator.GenerateEmptyHaulChainController" />
		<Publicize Include="Assembly-CSharp:UnusedTrainCarDeleter.AreDeleteConditionsFulfilled" />
		<Publicize Include="Assembly-CSharp:UnusedTrainCarDeleter.unusedTrainCarsMarkedForDelete" />
		<Publicize Include="Assembly-CSharp:StationProceduralJobsController.generationCoro" />
		<Publicize Include="Assembly-CSharp:StationController.availableJobs" />
		<Publicize Include="Assembly-CSharp:StationController.ExtractLogicTracks" />
		<Publicize Include="Assembly-CSharp:JobChainController.ReserveRequiredTracks" />
		<Publicize Include="Assembly-CSharp:JobChainController.jobChain" />
		<Publicize Include="Assembly-CSharp:JobChainController.jobDefToCurrentlyReservedTracks" />
		<Publicize Include="Assembly-CSharp:DV.Logic.Job.SequentialTasks.tasks" />
		<Publicize Include="Assembly-CSharp:StationController.stationRange" />
		<Publicize Include="Assembly-CSharp:DV.Logic.Job.TransportTask.destinationTrack" />
		<Publicize Include="Assembly-CSharp:DV.Logic.Job.TransportTask.carsPerDestinationTrack" />
		<Publicize Include="Assembly-CSharp:TrainCar.carStateSave" />
		<Publicize Include="Assembly-CSharp:TrainCar.trainPlatesCtrl" />
		<Publicize Include="Assembly-CSharp:TrainCar.carDebtController" />
		<Publicize Include="Assembly-CSharp:TrainCar.CarDamage" />
		<Publicize Include="Assembly-CSharp:TrainCar.CargoDamage" />
		<Publicize Include="Assembly-CSharp:CarStateSave.debtTrackerCar" />
		<Publicize Include="Assembly-CSharp:TrainCarPlatesController.UpdateCarHealthData" />
		<Publicize Include="Assembly-CSharp:TrainCarPlatesController.UpdateCargoHealthData" />
		<Publicize Include="Assembly-CSharp:JobSaveManager.GetYardTrackWithId" />
		<Publicize Include="Assembly-CSharp:JobSaveManager.LoadJobChain" />
		<Publicize Include="Assembly-CSharp:DV.Logic.Job.TrackID.trackType" />
		<Publicize Include="Assembly-CSharp:DV.Logic.Job.JobsManager.jobToJobCars" />
		<Publicize Include="Assembly-CSharp:CarsSaveManager.InstantiateCarFromSavegame" />
		<Publicize Include="Assembly-CSharp:CarsSaveManager.RestoreCarConnections" />
		<Publicize Include="Assembly-CSharp:CarsSaveManager.IgnoreTrainStressForLoadedCarsUntilCouplingIsSettled" />
		<Publicize Include="Assembly-CSharp:CarsSaveManager.SetBrakesOnSpawn" />
		<Publicize Include="Assembly-CSharp:DV.ServicePenalty.CarDebtController.trainCar" />
		<Publicize Include="Assembly-CSharp:DV.ServicePenalty.CarDebtController.ignoreCarDamageDebt" />
		<Publicize Include="Assembly-CSharp:DV.ServicePenalty.CareerManagerDebtController.currentNonZeroPricedDebts" />
		<Publicize Include="Assembly-CSharp:DV.ServicePenalty.JobDebtTracker.carsDebtTrackers" />
		<Publicize Include="Assembly-CSharp:DV.ServicePenalty.DebtComponent.type" />
		<Publicize Include="Assembly-CSharp:DV.ServicePenalty.DebtComponent.startValue" />
		<Publicize Include="Assembly-CSharp:DV.ServicePenalty.DebtComponent.snapshotValue" />
		<Publicize Include="Assembly-CSharp:DV.ServicePenalty.DebtComponent.endValue" />
		<Publicize Include="Assembly-CSharp:DV.ServicePenalty.DebtTrackerCar.carDmg" />
		<Publicize Include="Assembly-CSharp:DV.ServicePenalty.DebtTrackerCar.cargoDmg" />
		<Publicize Include="Assembly-CSharp:DV.ServicePenalty.DebtTrackerCar.debtData" />
		<Publicize Include="Assembly-CSharp:DV.Simulation.Cars.SimController.train" />
		<Publicize Include="Assembly-CSharp:DV.Simulation.Cars.SimController.OnLogicCarInitialized" />
	</ItemGroup>
	<!--
	Post-build deployment to Derail Valley.
  -->
	<Target Name="PostBuildCopyWithBackup" AfterTargets="Build">
		<PropertyGroup>
			<DeployDir>$(DvInstallDir)\Mods\PersistentJobsMod\</DeployDir>
			<DeployDll>$(DeployDir)$(TargetFileName)</DeployDll>
			<DeployPdb>$(DeployDir)$(TargetName).pdb</DeployPdb>
			<BackupDll>$(DeployDll).OLD</BackupDll>
		</PropertyGroup>
		<!-- Backup existing DLL -->
		<Move SourceFiles="$(DeployDll)" DestinationFiles="$(BackupDll)" Condition="Exists('$(DeployDll)')" />
		<!-- Copy DLL -->
		<Copy SourceFiles="$(TargetPath)" DestinationFiles="$(DeployDll)" />
		<!-- Copy PDB -->
		<Copy SourceFiles="$(TargetDir)$(TargetName).pdb" DestinationFiles="$(DeployPdb)" Condition="Exists('$(TargetDir)$(TargetName).pdb')" />
	</Target>
</Project>